# coding: utf-8
from pupa.scrape import Scraper

from utils import lxmlize, CanadianLegislator as Legislator

import re

SOURCE_URL = 'http://nslegislature.ca/index.php/people/members/'


class NovaScotiaPersonScraper(Scraper):

  def get_people(self):
    page = lxmlize(SOURCE_URL)
    for row in page.xpath('//div[@id="content"]/table/tbody/tr'):
      full_name, party, post = row.xpath('./td//text()')[:3]
      name = ' '.join(reversed(full_name.split(',')))
      detail_url = row[0][0].attrib['href']
      image, phone = get_details(detail_url)
      p = Legislator(name=name, post_id=post, role='MLA', image=image)
      p.add_source(SOURCE_URL)
      p.add_source(detail_url)
      p.add_contact('voice', phone, 'legislature')
      yield p

def get_details(url):
  page = lxmlize(url)
  image = page.xpath('string(//img[@class="portrait"]/@src)')
  # this is generated by JS, grrr
  #email = page.xpath('string(//span[contains(@id, "eeEncEmail")])')
  phone = page.xpath('string(//dd[@class="numbers"]/text())').split(': ')[1]
  return image, phone

