from utils import CanadianJurisdiction
from opencivicdata.divisions import Division
from pupa.scrape import Organization


class TorontoCandidates(CanadianJurisdiction):
    classification = 'executive'  # just to avoid clash
    division_id = 'ocd-division/country:ca/province:on'
    division_name = 'Toronto'
    name = 'Toronto City Council'
    url = 'http://www.toronto.ca'
    parties = [
        {'name': "Alliance Party of Ontario"},
        {'name': "Cultural Action Party of Ontario"},
        {'name': "Canadians' Choice Party"},
        {'name': "Communist Party of Canada (Ontario)"},
        {'name': "Equal Parenting Party"},
        {'name': "Freedom Party of Ontario"},
        {'name': "Green Party of Ontario"},
        {'name': "New Democratic Party of Ontario"},
        {'name': "None of the Above Direct Democracy Party"},
        {'name': "Northern Ontario Party"},
        {'name': "Ontario Liberal Party"},
        {'name': "Ontario Libretarian Party"},
        {'name': "Ontario Moderate Party"},
        {'name': "Ontario Provincial Confederation of Regions Party"},
        {'name': "Party for People with Special Needs"},
        {'name': "Pauper Party of Ontario"},
        {'name': "Progressive Conservative Party of Ontario"},
        {'name': "Stop the New Sex-Ed Agenda"},
        {'name': "The Peoples Political Party"},
        {'name': "Trillium Party of Ontario"},
        {'name': "Vegan Environmental Party"},
        {'name': "Independent"},
    ]
    skip_null_valid_from = True
    valid_from = '2018-09-19'
    member_role = 'candidate'

    def get_organizations(self):
        organization = Organization(self.name, classification=self.classification)

        divisions = {
            'Ajax',
            'Algoma—Manitoulin',
            'Aurora—Oak Ridges—Richmond Hill',
            'Barrie—Innisfil',
            'Barrie—Springwater—Oro-Medonte',
            'Bay of Quinte',
            'Beaches—East York',
            'Brampton Centre',
            'Brampton East',
            'Brampton North',
            'Brampton South',
            'Brampton West',
            'Brantford-Brant',
            'Bruce—Grey—Owen Sound',
            'Burlington',
            'Cambridge',
            'Carleton',
            'Chatham-Kent—Leamington',
            'Davenport',
            'Don Valley East',
            'Don Valley North',
            'Don Valley West',
            'Dufferin—Caledon',
            'Durham',
            'Eglinton—Lawrence',
            'Elgin—Middlesex—London',
            'Etobicoke Centre',
            'Etobicoke North',
            'Etobicoke—Lakeshore',
            'Flamborough—Glanbrook',
            'Glengarry—Prescott—Russell',
            'Guelph',
            'Haliburton—Kawartha Lakes—Brock',
            'Hamilton Centre',
            'Hamilton East—Stoney Creek',
            'Hamilton Mountain',
            'Hamilton West—Ancaster—Dundas',
            'Haldimand—Norfolk',
            'Hastings—Lennox and Addington',
            'Humber River—Black Creek',
            'Huron—Bruce',
            'Kanata—Carleton',
            'Kenora—Rainy River',
            'Kiiwetinoong',
            'King—Vaughan',
            'Kingston and the Islands',
            'Kitchener—Conestoga',
            'Kitchener Centre',
            'Kitchener South—Hespeler',
            'Lambton—Kent—Middlesex',
            'Lanark—Frontenac—Kingston',
            'Leeds—Grenville—Thousand Islands and Rideau Lakes',
            'London—Fanshawe',
            'London North Centre',
            'London West',
            'Markham—Stouffville',
            'Markham—Thornhill',
            'Markham—Unionville',
            'Milton',
            'Mississauga East—Cooksville',
            'Mississauga—Erin Mills',
            'Mississauga—Lakeshore',
            'Mississauga—Malton',
            'Mississauga—Streetsville',
            'Mushkegowuk—James Bay',
            'Nepean',
            'Newmarket—Aurora',
            'Niagara Centre',
            'Niagara Falls',
            'Niagara West',
            'Nickel Belt',
            'Nipissing',
            'Northumberland—Peterborough South',
            'Oakville',
            'Oakville North—Burlington',
            'Orléans',
            'Oshawa',
            'Ottawa—Vanier',
            'Ottawa Centre',
            'Ottawa South',
            'Ottawa West—Nepean',
            'Oxford',
            'Parkdale—High Park',
            'Parry Sound—Muskoka',
            'Perth—Wellington',
            'Peterborough—Kawartha',
            'Pickering—Uxbridge',
            'Renfrew—Nipissing—Pembroke',
            'Richmond Hill',
            'Sarnia—Lambton',
            'Sault Ste. Marie',
            'Scarborough Centre',
            'Scarborough North',
            'Scarborough Southwest',
            'Scarborough—Agincourt',
            'Scarborough—Guildwood',
            'Scarborough—Rouge Park',
            'Simcoe North',
            'Simcoe—Grey',
            'Spadina—Fort York',
            'St. Catharines',
            'Stormont—Dundas—South Glengarry',
            'Sudbury',
            'Thornhill',
            'Thunder Bay—Atikokan',
            'Thunder Bay—Superior North',
            'Timiskaming—Cochrane',
            'Timmins',
            'Toronto',
            'Toronto Centre',
            'Toronto—Danforth',
            'Toronto—St. Paul\'s',
            'University—Rosedale',
            'Vaughan—Woodbridge',
            'Waterloo',
            'Wellington—Halton Hills',
            'Whitby',
            'Willowdale',
            'Windsor—Tecumseh',
            'Windsor West',
            'York Centre',
            'York South—Weston',
            'York—Simcoe',
        }

        for division_name in divisions:
            organization.add_post(role='candidate', label=division_name, division_id=self.division_id)

        yield organization
